### ISSUE TITLE
rice.cds does not exist

### ISSUE THREAD

**Issue by IBEXCluster** [chenym1/genetribe#5]
We are running an example dataset and it's failed with `"rice.cds does not exist"`. 
Any advise? 

Here is the complete log file:

```
$ genetribe core -l aet -f rice 

   ===============================
  ||                             ||
  ||         GeneTribe           ||
  ||       Version: v1.2.0       ||
  ||                             ||
   ===============================

2022-03-10 15:24:03 ...prepare files...
2022-03-10 15:28:13 ...calculate BSR, CBS and Penalty...

15:33:33 [base] Set text.usetex=False. Font styles may be inconsistent.
Traceback (most recent call last):
  File "/ibex/scratch/projects/c2072/work/genetribe/miniconda3/envs/genetribe.env1/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/ibex/scratch/projects/c2072/work/genetribe/miniconda3/envs/genetribe.env1/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/ibex/scratch/projects/c2072/work/genetribe/miniconda3/envs/genetribe.env1/lib/python3.5/site-packages/jcvi/compara/catalog.py", line 939, in <module>
    main()
  File "/ibex/scratch/projects/c2072/work/genetribe/miniconda3/envs/genetribe.env1/lib/python3.5/site-packages/jcvi/compara/catalog.py", line 80, in main
    p.dispatch(globals())
  File "/ibex/scratch/projects/c2072/work/genetribe/miniconda3/envs/genetribe.env1/lib/python3.5/site-packages/jcvi/apps/base.py", line 111, in dispatch
    globals[action](sys.argv[2:])
  File "/ibex/scratch/projects/c2072/work/genetribe/miniconda3/envs/genetribe.env1/lib/python3.5/site-packages/jcvi/compara/catalog.py", line 676, in ortholog
    last_main([bfasta, afasta, cpus_flag], dbtype)
  File "/ibex/scratch/projects/c2072/work/genetribe/miniconda3/envs/genetribe.env1/lib/python3.5/site-packages/jcvi/apps/align.py", line 536, in last
    dbtype=dbtype,
  File "/ibex/scratch/projects/c2072/work/genetribe/miniconda3/envs/genetribe.env1/lib/python3.5/site-packages/jcvi/utils/cbook.py", line 100, in wrapper
    "The specified infile `{0}` does not exist".format(x)
AssertionError: The specified infile `rice.cds` does not exist
```

**Comment by chenym1** [comment]
You can checked the dependencies and environment, especially the BLAST program.

**Comment by Wangchangsh** [comment]
I got the same error.

Here is my dependencies version.
```
bedtools v2.29.2
JCVI utility libraries v1.0.6
blast 2.9.0, build Mar 11 2019 15:20:05
```

**Comment by Ian1512** [comment]
I got the same error.

**Comment by Wangchangsh** [comment]
use conda or docker(`https://hub.docker.com/r/changshengw6/genetribe`)

**Comment by Ian1512** [comment]
Thank your answer!
I have another problem:
You use ‘sh(' '.join(['cat',name1+'.chrlist','>',out_dic+name1+'_'+name2+'.matchlist']))’ in /home/hjzhang/soft/genetribe/bin/corelns to get the file output/*.matchlist:

my “output/*.matchlist” like the picture:

The right result have been:
 
The error lead the “list index out of range” in coreSplitbyChromsomeGroup:


 

Thank your help again!
Zhanghuajian 


发件人: Wangchangsh
发送时间: 2023年3月2日 17:19
收件人: chenym1/genetribe
抄送: Ian1512; Comment
主题: Re: [chenym1/genetribe] rice.cds does not exist (Issue #5)

use conda or docker(https://hub.docker.com/r/changshengw6/genetribe)

**Comment by libmelo** [comment]
> https://hub.docker.com/r/changshengw6/genetribe

Do you solve it? I still get the err even with the docker image. The same error in my own conda env.

OK. I solved it. Firstly, the docker image can avoid the err of latex suits(cased by MCscan), but it can do nothing for this.
And err of xxx.cds could be solved as follows:
1. Make seqs id in the xxx.fa the same as the gene id in xxx.bed
2. Discard the seqs with gene id not in the xxx.bed (It shold be none, but I write the rule in my scripts and not check it)
3. According to 1. Only keep one seq for one gene. (Of course, if you do 1., this is resonable)
I am not sure which effected, but it's done after I write the script to deal.

**Comment by IBEXCluster** [comment]
Looks, I was able to get progress on this testing. However, I need to fix some Perl and text formatting issues. 

> 2024-03-19 08:48:24 ...prepare files...
> 2024-03-19 09:36:38 ...calculate BSR, CBS and Penalty...
>  Naga: In for loop
>  Naga: /ibex/sw/csi/genetribe/1.2.0/el7.9_conda/genetribe/bin/coreCalculateScore -i aet_rice.blast2 -m aet_rice.matchlist -a aet.bed -b rice.bed --oa aet_aet.blast2 --ob rice_rice.blast2   -o aet_rice.chrinfo > aet_rice.score1 
> 
> [09:36:56] ERROR    Set text.usetex=False. Font styles may be inconsistent.                                                                                                                                   base.py:402
>            DEBUG    Assuming --qbed=aet.bed --sbed=rice.bed                                                                                                                                                synteny.py:499
>            DEBUG    Load file `aet.bed`                                                                                                                                                                        base.py:34
>            DEBUG    Load file `rice.bed`                 
>            ....

**Comment by Liantaotao** [comment]
I had the same problem, and checking revealed that there was a problem with the format of the protein sequence that prevented makeblastdb from running successfully, but no errors were reported in that pipeline.
"BLAST Database creation error: near line 180868, there's a line that doesn't look like plausible data, but it's not marked as defline orcomment." 
Removing the error sequence solved the problem (iwgsc_refseq_v2.1)
